[versions]
h2 = '1.4.200'
hibernate-ehcache = '5.6.14.Final'
javaparser = '3.24.8'
jaxb-api = '2.3.1'
mongodb = '4.8.0'
netty-native = '4.1.85.Final'
testcontainers = '1.17.6'
tomcat-jdbc = '10.1.2'

micronaut-docs = "2.0.0"
micronaut = "4.0.0-SNAPSHOT"
micronaut-test = "4.0.0-SNAPSHOT"
groovy = "4.0.6"
spock = "2.2-groovy-4.0"

# Plugins
micronaut-gradle-plugin = "3.6.6"

[libraries]
h2 = { module = 'com.h2database:h2', version.ref = 'h2' }
hibernate-ehcache = { module = 'org.hibernate:hibernate-ehcache', version.ref = 'hibernate-ehcache' }
javaparser = { module = 'com.github.javaparser:javaparser-core', version.ref = 'javaparser' }
jaxb-api = { module = 'javax.xml.bind:jaxb-api', version.ref = 'jaxb-api' }
mongodb-driver-sync = { module = 'org.mongodb:mongodb-driver-sync', version.ref = 'mongodb' }
netty-native = { module = 'io.netty:netty-transport-native-epoll', version.ref = 'netty-native' }
testcontainers-spock = { module = 'org.testcontainers:spock', version.ref = 'testcontainers' }
tomcat-jdbc = { module = 'org.apache.tomcat:tomcat-jdbc', version.ref = 'tomcat-jdbc' }

groovy-test = { module = 'org.apache.groovy:groovy-test', version = '' }

# Plugins
gradle-micronaut = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }
