[versions]
javaparser = '3.26.1'

micronaut-docs = "2.0.0"
micronaut = "4.6.1"
micronaut-test = "4.5.0"
groovy = "4.0.18"
spock = "2.3-groovy-4.0"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

javaparser = { module = 'com.github.javaparser:javaparser-core', version.ref = 'javaparser' }

groovy-test = { module = 'org.apache.groovy:groovy-test', version = '' }
